### ISSUE TITLE
feat: Add an API that allows immediate execution first then tick the timer

### ISSUE THREAD

**Issue by cangSDARM** [mdsherry/clokwerk#24]
In my case, after setting `every(1.minutes())`, it always starts after 1 minute of execution.
If I setting `every(10.minutes())`, it starts after 10 minutes.

Maybe you can consider adding an API that allows immediate execution first then tick the timer?

```rust
let mut scheduler = Scheduler::new();

scheduler
        .every(10.minutes())
        .run(|| {
            println!("execution");
        });

scheduler.exe_first(true);  //Like this?
//Or, this?
scheduler.immediate_run(true);
```

**Comment by mdsherry** [comment]
Why not
```rust
let mut scheduler = Scheduler::new();
let my_task  = || {
  println!("execution");
};
my_task();
scheduler
        .every(10.minutes())
        .run(my_task);
```
?

**Comment by cangSDARM** [comment]
This is ok, but I think this is a bit ugly

If you accept or add a note in the document

**Comment by mdsherry** [comment]
The other thing is that with a schedule of `every(10.minutes())`, it *doesn't* wait for 10 minutes before running. It will run at the next multiple of 10 minutes since midnight. One advantage of this is that it if your program restarts at, e.g. 9:55, it will still run the task at 10:00 as expected. If you start running the task on start-up as well, there will be an extra execution.
