### ISSUE TITLE
How to retry correctly in each round?

### ISSUE THREAD

**Issue by cangSDARM** [mdsherry/clokwerk#25]
For example, I have a task like this:

```rust
fn task() {
   let ret: Result<(), Error> = may_fault_task();
   match ret {
      Ok() => (),
      Err(_) => {
        //I want retry this task,
        () 
      }
   };
}

///--------------- Scheduler and its handler
let mut scheduler = Scheduler::new();

    scheduler
        .every(1.minutes())
        .run(|| task() );

let handle_thread = scheduler.watch_thread(Duration::from_millis(100));

println!("Running scheduler...");

loop {
   thread::sleep(Duration::from_micros(100));
}
```

But I don't know how to retry correctly in `task`.

----

Should I call the `task` directly and recursively, or how?

If it times out during the retry (more than 1 minute and the next timer has been triggered), will it automatically skip the task or continue until some internal event triggers the shutdown?

**Comment by mdsherry** [comment]
The scheduler is blocked while tasks are being run. If your task takes a long time, it can prevent not only its next run, but also any other scheduled tasks.

Here's an example: let's say we have
```rust
let mut scheduler = Scheduler::new();

scheduler.every(1.minutes()).run(|| fast_task());
scheduler.every(1.minutes()).run(|| slow_task());
scheduler.every(1.minutes()).run(|| another_fast_task());

let handle = scheduler.watch_thread(Duration::from_millis(100));

// wait until program is done
```

At 12:00:00.000, it will run `fast_task`, then `slow_task`, then `another_fast_task`. Let's say that `fast_task` took 10ms, `slow_task` took 10s, and `another_fast_task` took only 1 ms. After executing each task, the scheduler will reschedule it for its next time. All three tasks have a frequency of 1 minute, so the next run time is 12:01:00.000. The current time is 12:00:10.011.

At 12:00:10.111, the scheduler wakes again, finds no tasks to run, and goes back to sleep for another 100 ms. This repeats until 12:01:00.011, when it finds three tasks pending. `fast_task` is fast again (8 ms), but this time `slow_task` takes 90 seconds to run! `another_fast_task` again lives up to its name (1 ms). Regardless, all three are scheduled to run again at 12:02:00.000. The current time is 12:02:30.020.

At 12:02:30.120, the scheduler wakes and finds all three tasks again ready to run again! It runs them, and reschedules them. Let's say `slow_task` was slow again, and now the current time is 12:04:05.123. Even though it's in the past, it's still going to schedule them for 12:03:00.000, because that was the next time to use when the tasks started.

At 12:04:05.223, the scheduler runs, runs the three delayed task (they were supposed to run over a minute ago!), and goes to reschedule them. This time it reschedules them for 12:05:00.000. We've skipped the 12:04:00 run, because it was in the past at the point we started running the tasks.

---

It's generally recommended to move slow tasks to a separate thread, so that they don't block other tasks from running on time. In your case, you might find something like 
```rust
use parking_lot::{Mutex, Condvar};
use std::sync::Arc;
use std::thread;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum TaskState {
  Waiting,
  DoTheThing,
  Done
};

let pair = Arc::new((Mutex::new(Waiting), Condvar::new()));
let pair2 = pair.clone();

thread::spawn(move|| {
  let &(ref lock, ref cvar) = &*pair2;
  loop {
    // Do this next bit in its own block so that we release the mutex before we start on the task itself.
    {
      let mut state = lock.lock();
      if *state == TaskState::Waiting {
        // Wait to be woken by the scheduler
        cvasr.wait(&mut state);
      }
      match *state {
        TaskState::Waiting => continue, // That's odd, but I guess we'll just start waiting again
        TaskState::Done => return, // We're finished, so exit the thread
        TaskState::Working => *state = TaskState::Waiting // reset the state for next run.
      }
      // Note that we reset the state at the start, so that, if we run over time and we're re-scheduled, we run immediately
    }
    // At this point, our state should have been `Working`, so do our task:
    loop {
      let result = fallible_operation();
      match result {
        Ok(_) => break, // don't retry
        Err(_) => () // retry
      }
    }
  }
});

let mut scheduler = Scheduler::new();

let pair3 = pair.clone();
scheduler
    .every(1.minutes())
    .run(|| {
      let &(ref lock, ref cvar) = &*pair3;
      let mut state= lock.lock();
      *state = TaskState::Working;
      cvar.notify_one();
    });

let handle_thread = scheduler.watch_thread(Duration::from_millis(100));

// Do other things

// Time to quit
// Drop the scheduler first so it doesn't accidentally clobber our "Done" state with "Working".
// You could also add a check in the task itself so it only changes Waiting to Working.
std::mem::drop(handle_thread);
let &(ref lock, ref cvar) = &*pair;
let mut state= lock.lock();
*state = TaskState::Done;
cvar.notify_one();
```

**Comment by cangSDARM** [comment]
This is an excellent example! I recommend to pin this issue directly or add it to the doc to remind others.
